### ISSUE TITLE
[Critical] Fix any compilation errors before pushing to the repo

### ISSUE THREAD

**Issue by qsjiang** [CMPUT301W15T12/C301Project#11]
Hey guys,

Make sure to add all the necessary classes/layouts for your jUnit tests to compile. 
Otherwise your teammates won't even be able to run their tests without deleting yours first.   
> You don't need to actually implement those activities, just make sure it is there and can be addressed inside the jUnit test. I know for this assignment we can probably get away without running the tests at all, but it is still crucial to run them just for the feedbacks that they actually work.

![1e309eac-18a7-4a10-8c8b-211cd80ec927](https://cloud.githubusercontent.com/assets/6367081/6186791/8d35dc9a-b33b-11e4-9931-c770a513a9fd.png)

**Comment by Pengwin-man** [comment]
yeah i get this problem too. please make sure everything required for the code to run is included so we can edit our test cases and make sure they fail. i cant test anything like this.

**Comment by vanbelle** [comment]
i just commented out the tests that werent mine, so as not to mess up what anybody else was working on, the tests run that way. you can always try that.

**Comment by megsum** [comment]
I am almost done fixing it so there are no errors! 10 minutes!

**Comment by megsum** [comment]
Never mind they arn't my errors and somebody else may be working on them :/

**Comment by megsum** [comment]
Okay so it says there are no more errors on mine, but the Android.XML file is missing apparently. Does anyone know how to fix that?

**Comment by qsjiang** [comment]
Hi Megan,

Have you resolved the problem yet? 
The Android.XML is not missing inside the repo, maybe its accidentally deleted inside your local copy? 
If that is the case, save all your un-staged changes and try to clone a fresh repo, see if that helps.

Jim

**Comment by qsjiang** [comment]
Although the Android.XML is not missing, but there was an error inside the values-14/styles.xml file. 

After some investigation, and it looks like some how the project target android version is set to 3.0 api level 11 which causes the level 14 styles.xml not be able to load the theme it needs.

After setting the target api level to 17 (Android 4.2 the version used on the lab machine) the bug is resolved. (see more details in commit e8dc6c6c677565116a5739d08ff86298e262e8fb)

Let me know if this helps with the problem you have earlier. 

Jim
