### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#16]
Document your initial object-oriented analysis and design using a UML class diagram (or diagrams), focusing on the most important anticipated classes, interfaces, and relationships. Include detail on key attributes and methods. Include notes on the use of design patterns among the classes. Add notes if the purpose of a class or interface is likely not clear to an outsider. The diagram(s) may be reverse engineered from the code, but must be edited, arranged, and selective (not a raw dump). The diagram(s) must be neat and tidy, and drawn well using tools like eUML2 and dia and embedded as image(s) in your team wiki.

**Comment by vanbelle** [comment]
A list of the classes currently implemented in our code that I think needs to be in the UML:
User List
User
Claim list
Claim
Expense List
Expense Item
Amt - Currency
Any others???

**Comment by qsjiang** [comment]
FYI. I will be working on user list and user. 
The URML diagram will be created using DIA, and I will upload the dia files to the google drive one its finished. (and image to the wiki)

**Comment by qsjiang** [comment]
Since all the models inside an UML diagram are closely coupled, all the models above need to be connected inside one single UML diagram.

In order for use to do this we need to use the same software, and copy paste them onto the same file.

So make sure to use DIA, so we can merge the diagram later.

**Comment by Pengwin-man** [comment]
why don't we just use the built-in eclipse extension to make the diagram? it will do it for us and all we have to worry about is formatting it. i think it will be better. I can do it in 30 sec on my computer. I think it is better than having all different diagrams to merge. if we do it with eclipse, we can do it on Tuesday at our meeting( I will bring my laptop) and I can show you how to do it. we can then edit it and it will create a separate UML file.  There is no need to complicate things.  What do you guys think?

**Comment by Pengwin-man** [comment]
i will do Claim and ClaimList then.  

Make sure we send everything to Jim so he can put everything together afterwards

**Comment by qsjiang** [comment]
My email: qsjiang@ualberta.ca

**Comment by Pengwin-man** [comment]
make sure we are not adding any unnecessary getters and setters in the UML. it should only include add/remove/boolean methods. otherwise it will get really cluttered

**Comment by megsum** [comment]
Should we worry about listeners in the UML?

**Comment by LeahGabrielle** [comment]
Uh, is there anything I can do with the UML?

**Comment by vanbelle** [comment]
Could you maybe do the storyboard? That would be useful.

**Comment by LeahGabrielle** [comment]
yep. I can work on that.

**Comment by vanbelle** [comment]
When I was rereading the USs about tags it seemed like the list of tags should be independent of each individual claim, so that when assigning tags to a claim they are just chosen from a previously created list of tags.To fit this model I added a button on the ClaimList page so that the user could add/remove tags from a tag list. This seems to fit better with US03.02. What do you think?

**Comment by Pengwin-man** [comment]
Just make a list as an attribute in the claim class.  That would solve all
the problems of not sharing tags

**Comment by vanbelle** [comment]
But that wouldn't work in the case where a tag is created but not associated with a claim

**Comment by Pengwin-man** [comment]
Why I mean is add a tag to the claim taglist every time you associate one
with it. Other than that it stays in 'storage'  in the taglist class

**Comment by vanbelle** [comment]
ok, that makes more sense. In that case though we will need to add a class Tag List to the UML.
