### ISSUE TITLE
Addressing TA feedback

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#17]
![use case](https://cloud.githubusercontent.com/assets/9437242/6273268/38756d7a-b82b-11e4-8c98-f628ce4709fc.png)
TA's Feedback with bullet points to make sure we get it all
- [x] US03.01.01: System should show the list of available tags, so that the user can see if he/she can select one from that list. - Sarah
- [x] US03.03.01: Here the input must be in form of checkbox or something similar, so that a user can select one or more tags from the list. - Sarah
- [x] US04.08.01: how did you deal with minimal required navigation? I think you should ask the customer about this, it's a little bit confusing. 
- [x] US06.02.01: System should not show an error message. It's just there is no photo. 
- [x] US08.01.01, US08.02.01, US08.04.01: why there is no postcondition? - Sarah
- [x] US08.05.01: Is there no postcondition ?? !! - Sarah
- [x] US08.09.01: Precondition---- and Approver is not the Claimant. - Sarah
- [x] US09.01.01: Postcondition: expense/item is saved locally and will be uploaded automatically after getting the connection.   - Sarah

It is hard to mention all the cases individually. So now it's the duty of all of you to read again and fix problems. 

Test cases:
I am not happy with the organization. I can not find all the text cases for all use cases, may be they are there, but it should not be hard to find them.

- [x] So I want test case with use case in the wiki together. 
One use case followed by one test case for example. See the attachment as an example. 

The preconditions and postconditions must be checked in the test cases. 

Mockups: 
- [x] Describe each page. What is this page for? - Sarah
What does it have (e.g., which button for what purpose? ). 
You don't have to change much. Just add some description. 

Storyboard:

You just need a single story. 
- [x] Show one single story precisely: what is the user story (only one) and then show the sequence with description. 
For example: what would be the storyboard for US08.05.01 from the very beginning to the end, and you are done with the story board? 
I will check if your story board is consistent with the use case you described. 

- [x] Glossary: Where did you get this definitions from? any source?  - Sarah
- [x] Who is sysadmin in US06.04.01?

**Comment by vanbelle** [comment]
https://docs.google.com/a/ualberta.ca/presentation/d/1dprraJnOzSoNxau2TFjbsP5r-ipsdjT7sR1SO7at7Hw/edit#slide=id.g7833ce8c8_032

I added all the mockup details to the first 9 slides of our original storyboard slides.

**Comment by vanbelle** [comment]
Add your test cases to Use Cases in the wiki
- [ ] US02.01.01
- [ ] US02.02.01
- [ ] US03.01.01 updated 2015-02-09
- [ ] US03.02.01
- [ ] US03.03.01
- [ ] US04.01.01
- [ ] US04.02.01
- [ ] US04.03.01
- [ ] US04.04.01
- [ ] US04.05.01
- [ ] US04.06.01
- [ ] US04.07.01
- [ ] US04.08.01
- [ ] US05.01.01
- [ ] US06.01.01
- [ ] US06.02.01
- [ ] US06.03.01
- [ ] US06.04.01
- [ ] US07.01.01
- [ ] US07.02.01
- [ ] US07.03.01
- [ ] US07.04.01
- [ ] US07.05.01
- [ ] US08.01.01
- [ ] US08.02.01
- [ ] US08.03.01
- [ ] US08.04.01
- [ ] US08.05.01
- [ ] US08.06.01
- [ ] US08.07.01
- [ ] US08.08.01
- [ ] US08.09.01 
- [ ] US09.01.01

**Comment by vanbelle** [comment]
Change the storyboard so that each slide is a US.
- [ ] US01.01.01
- [ ] US01.02.01
- [ ] US01.03.01
- [ ] US01.04.01
- [ ] US01.05.01
- [ ] US01.06.01
- [ ] US02.01.01
- [ ] US02.02.01
- [ ] US03.01.01 updated 2015-02-09
- [ ] US03.02.01
- [ ] US03.03.01
- [ ] US04.01.01
- [ ] US04.02.01
- [ ] US04.03.01
- [ ] US04.04.01
- [ ] US04.05.01
- [ ] US04.06.01
- [ ] US04.07.01
- [ ] US04.08.01
- [ ] US05.01.01
- [ ] US06.01.01
- [ ] US06.02.01
- [ ] US06.03.01
- [ ] US06.04.01
- [ ] US07.01.01
- [ ] US07.02.01
- [ ] US07.03.01
- [ ] US07.04.01
- [ ] US07.05.01
- [ ] US08.01.01
- [ ] US08.02.01
- [ ] US08.03.01
- [ ] US08.04.01
- [ ] US08.05.01
- [ ] US08.06.01
- [ ] US08.07.01
- [ ] US08.08.01
- [ ] US08.09.01 
- [ ] US09.01.01

**Comment by qsjiang** [comment]
implemented all the feedbacks regarding US06.0x.0x

**Comment by LeahGabrielle** [comment]
I've done the storyboard and added it to the wiki as well as put up the mockup with Sarah's changes.
