### ISSUE TITLE
[Merge UML] Make sure to use DIA when making UML diagrams

### ISSUE THREAD

**Issue by qsjiang** [CMPUT301W15T12/C301Project#19]
I mentioned this inside the UML issue, but I put it here just to make sure everyone can see it. 

Since all the models inside an UML diagram are closely coupled, they need to be placed onto one single diagram if we want to draw connections between them. 

The easiest way to merge all diagrams is to draw our models using the same software and later copy paste them onto one single diagram. 

So make sure to use DIA, and we will merge the diagrams on Monday.

**Comment by Pengwin-man** [comment]
I think we should just use 1 version made on tuesday together.  This way there is no confusion. we can use eclipse add-on to do that, and it wil take us 30 min tops to make and edit the entire thing.

**Comment by qsjiang** [comment]
@Pengwin-man  
The assignment is due on Monday. we won't have time to wait till Tuesday.

Right now the tool everyone is familiar with is DIA, maybe for the future project you can show us the eclipse UML feature.

**Comment by Pengwin-man** [comment]
Oh. right. i must have gotten the dates mixed up. you can still do it with Eclipse. it is still faster. then all we have to do is decide what stays.  We dont need everyone to make a specific UML. since we have the classes we need already, I can just make one and upload it to git, and then you can make all the cahnges you want to it, removing any classes that are unnecessary and adding stuff that is missing.      
it would be better than using a 3rd pary software i dont have on my computer

**Comment by qsjiang** [comment]
@Pengwin-man 

The problem with eclipse is it automatically generates the UML according to the current model classes(correct me if i am wrong), but right now most of the model classes are just placeholders with setters and getters. Some of the models are just simply wrong. 

In the end you would end up throwing away most of the auto generated UML

and DIA is here http://dia-installer.de/    I downloaded on my MAC it works pretty smooth,

**Comment by qsjiang** [comment]
@Pengwin-man 
And most importantly, I personally have never touch eclipse UML plugin before, and have not clue how to use it. I am pretty sure most of the team would feel the same way.

**Comment by Pengwin-man** [comment]
ill work on some classes and see what we can do. erm. yeah. ill email you what I have and you can put everything together later then.

**Comment by qsjiang** [comment]
@Pengwin-man  The thing is, most of the team member me included probably have never used eclipse UML plugin before. 

I was hoping you can give us a tutorial during a sit down meeting before we start using it. but right now we don't have the time for a sit down meeting.

**Comment by Pengwin-man** [comment]
like I said. i will use DIA for now since we are short on time.  I will email you my file and you can merge it with yours.
