### ISSUE TITLE
tag test case missing

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#21]
US03.03.01 - MISSING
As a claimant, I want to filter the list of expense claims by tags, to show only those claims that have at least one tag matching any of a given set of one or more filter tags.

There is also some TA feedback regarding your tag Use Cases that hasn't been addressed. I made a suggestion in the UML issue(#16) about how I would handle the tags if that helps.

Then please add the tag test cases to Use cases. If you create a tag list separate from the claims themselves, I would expect that you'd need 5-6 test cases and you only have 4 written.

**Comment by Pengwin-man** [comment]
I'll get on it S soon as I get off work

**Comment by vanbelle** [comment]
If we have an ArrayList tagList inside of Claim and a class Taglist for all the available tags, you will need separate test cases for adding tags. One for US03.01 to make sure its associated with a claim and one for US03.02 to make sure the user can add new tags to be available to claims..

**Comment by Pengwin-man** [comment]
i can edit the test case as well

**Comment by Pengwin-man** [comment]
i extended the test case so that it adds to both the claim if we want to add to the claim, or the taglist if we want to only create a tag. i did not go into details. i just made 2 separate add methods each adding to its own list. i did not make any specific conditions of scenarios. i will work on those later.

for the filtering, i am just going to add everthing in a new list that matches the typed tag and display that.

**Comment by Pengwin-man** [comment]
I added the filter test case. It is not its own test case though, and is just a few extra lines added to the existing addTag test case.  Since everything was already in place, i just added it there. I can make it a standalone case when I have more things to work with.

**Comment by vanbelle** [comment]
for the filter test case just copy it again into the use cases and delete the line(s) pertaining to adding or put in a comment telling the TA that is where the test is. also the test cases (renaming/deleting) are still not posted to your second use case. please do those ASAP.

each use case should have a test case, or a comment of some kind acknowledging why there isnt a test case.

**Comment by Pengwin-man** [comment]
I'll do it right away.  I am pretty sure I posted it yesterday.  I will do
it again to make sure
