### ISSUE TITLE
Storyboard upload

### ISSUE THREAD

**Issue by LeahGabrielle** [CMPUT301W15T12/C301Project#24]
![storyboard-2](https://cloud.githubusercontent.com/assets/8978512/6335915/19bec9ce-bb5c-11e4-996b-11d8282a588d.png)  
![storyboard-2 1](https://cloud.githubusercontent.com/assets/8978512/6335921/29c17bc8-bb5c-11e4-9f8e-53c656f3dd3a.png)
![storyboard-2 2](https://cloud.githubusercontent.com/assets/8978512/6335922/2c3cd820-bb5c-11e4-899a-f46a51a9e605.png)
![storyboard-2 3](https://cloud.githubusercontent.com/assets/8978512/6335942/64c8defa-bb5c-11e4-8e54-ed9e88d58d34.png)
![storyboard-2 4](https://cloud.githubusercontent.com/assets/8978512/6335984/b9328f68-bb5c-11e4-8242-e051e060f503.png)
![storyboard-2 5](https://cloud.githubusercontent.com/assets/8978512/6335938/5ed1e9a6-bb5c-11e4-9978-4e7c636fa489.png)
![storyboard-2 6](https://cloud.githubusercontent.com/assets/8978512/6335988/be700c76-bb5c-11e4-8f0d-e1e8d536ce4f.png)
![storyboard-2 7](https://cloud.githubusercontent.com/assets/8978512/6335989/c0b06b5c-bb5c-11e4-8c12-eb8faf82646b.png)
![storyboard-2 8](https://cloud.githubusercontent.com/assets/8978512/6335993/c46305ac-bb5c-11e4-81c3-1d018dd83a9d.png)
![storyboard-2 9](https://cloud.githubusercontent.com/assets/8978512/6335996/c605b206-bb5c-11e4-9d2e-146976058100.png)
![storyboard-2 10](https://cloud.githubusercontent.com/assets/8978512/6335999/c7ce65c4-bb5c-11e4-9fd9-cf6f8c14c521.png)
![storyboard-2 11](https://cloud.githubusercontent.com/assets/8978512/6336006/d40b979e-bb5c-11e4-9571-a119c719bd64.png)

![storyboard](https://cloud.githubusercontent.com/assets/8978512/6336103/87df6aa2-bb5d-11e4-8ef6-f4efea01c6a2.png)
![storyboard 1](https://cloud.githubusercontent.com/assets/8978512/6336104/895bec16-bb5d-11e4-8c05-39dfdee0666e.png)
![storyboard 2](https://cloud.githubusercontent.com/assets/8978512/6336108/8b6bad5c-bb5d-11e4-878f-4986ae99eb01.png)
![storyboard 3](https://cloud.githubusercontent.com/assets/8978512/6336110/8f5a18a4-bb5d-11e4-98e4-9b2229b56bef.png)
![storyboard 4](https://cloud.githubusercontent.com/assets/8978512/6336112/92a51f86-bb5d-11e4-9996-892968ad2c9c.png)
![storyboard 5](https://cloud.githubusercontent.com/assets/8978512/6336115/9475a52e-bb5d-11e4-8a51-755d281a9138.png)
![storyboard 6](https://cloud.githubusercontent.com/assets/8978512/6336117/97e48c7a-bb5d-11e4-9265-9e6cdce0a69f.png)
![storyboard 7](https://cloud.githubusercontent.com/assets/8978512/6336118/991e8f96-bb5d-11e4-8bc8-7e7650933eb6.png)
![storyboard 8](https://cloud.githubusercontent.com/assets/8978512/6336119/9a47525e-bb5d-11e4-80ec-f044da4ef6b2.png)
![storyboard 9](https://cloud.githubusercontent.com/assets/8978512/6336120/9c930e5e-bb5d-11e4-9852-515dc7e2d0f1.png)
![storyboard 10](https://cloud.githubusercontent.com/assets/8978512/6336123/9f0f1f6a-bb5d-11e4-8036-469229d1342e.png)
![storyboard 11](https://cloud.githubusercontent.com/assets/8978512/6336124/a0a20464-bb5d-11e4-8bd1-a5c7edf8cad2.png)
![storyboard 12](https://cloud.githubusercontent.com/assets/8978512/6336126/a210379e-bb5d-11e4-8943-cb7320cda8c6.png)
![storyboard 13](https://cloud.githubusercontent.com/assets/8978512/6336128/a410a722-bb5d-11e4-8233-dbe63a95b2f4.png)
![storyboard 14](https://cloud.githubusercontent.com/assets/8978512/6336130/a55bd53e-bb5d-11e4-8275-8f16b495fe53.png)
![storyboard 15](https://cloud.githubusercontent.com/assets/8978512/6336131/a7c6f6fa-bb5d-11e4-835e-9819a3c2e9ad.png)
![storyboard 16](https://cloud.githubusercontent.com/assets/8978512/6336132/ab0b8f42-bb5d-11e4-96ea-60815cb2a38d.png)
![storyboard 17](https://cloud.githubusercontent.com/assets/8978512/6336135/abf9daa8-bb5d-11e4-95fa-87416bdb4207.png)
![storyboard 18](https://cloud.githubusercontent.com/assets/8978512/6336137/ad243fa4-bb5d-11e4-9edb-4b346724defa.png)
![storyboard 19](https://cloud.githubusercontent.com/assets/8978512/6336139/af45a2f0-bb5d-11e4-938c-33ee1078103e.png)
![storyboard 20](https://cloud.githubusercontent.com/assets/8978512/6336140/b0770e98-bb5d-11e4-9266-b6f13ebcc3f2.png)
![storyboard 21](https://cloud.githubusercontent.com/assets/8978512/6336143/b1e51dec-bb5d-11e4-8e0d-32afeb0f0d1b.png)
![storyboard 22](https://cloud.githubusercontent.com/assets/8978512/6336144/b3a1138e-bb5d-11e4-8858-e553c35102bc.png)
![storyboard 23](https://cloud.githubusercontent.com/assets/8978512/6336146/b4c9b6c6-bb5d-11e4-931b-c8d5ed08413c.png)
![storyboard 24](https://cloud.githubusercontent.com/assets/8978512/6336150/b607da18-bb5d-11e4-9004-38296d0a4b26.png)
![storyboard 25](https://cloud.githubusercontent.com/assets/8978512/6336152/b79c5f84-bb5d-11e4-80e6-9573d64e4b46.png)
![storyboard 26](https://cloud.githubusercontent.com/assets/8978512/6336153/b8b3608e-bb5d-11e4-9bfb-a55a4be30172.png)
![storyboard 27](https://cloud.githubusercontent.com/assets/8978512/6336155/bb16fe8a-bb5d-11e4-8fbd-a5ec3873d0ac.png)
![storyboard 28](https://cloud.githubusercontent.com/assets/8978512/6336156/bca9bd00-bb5d-11e4-9698-0c74b59dc898.png)
![storyboard 29](https://cloud.githubusercontent.com/assets/8978512/6336157/be61b896-bb5d-11e4-9ae8-34739c47ece3.png)
![storyboard 30](https://cloud.githubusercontent.com/assets/8978512/6336158/bf647350-bb5d-11e4-8062-356961d216a8.png)
![storyboard 31](https://cloud.githubusercontent.com/assets/8978512/6336159/c0840c8c-bb5d-11e4-8ef9-598ff81e978a.png)

**Comment by vanbelle** [comment]
I feel like we don't need to include the Login/ Create Account page and everything after that of the original storyboard.

Also this is what Abram said about User roles in response to a student asking "Is every user both a claimant and an approver? Or can a user be just an approver/ just a claimant?"
Abram: "A user can make claims AND/OR approve claims. "

So I would either add the page that lets the user choose between adding/approving claims, or during account creation we would probably have to have something to specify what kind of account was being opened. Approver/claimant, claimant, or approver.

**Comment by LeahGabrielle** [comment]
I understood his response as a user can be a claimant and a approver, only a claimant, or only an approver.
I am assuming that the user has already made an account and is only a claimant. I will add that in.
I've kept the stuff from the original storyboard for us as future reference.

**Comment by vanbelle** [comment]
But where does the User specify that he is only a Claimant, if that is part of the account creation step then thats fine and doesnt need to be shown in the storyboard, however it would need to be shown in the mockup of the create account page in that case. So we need to pick one or the other.

**Comment by LeahGabrielle** [comment]
![storyboard 32](https://cloud.githubusercontent.com/assets/8978512/6337194/7654db20-bb65-11e4-92f5-d606d8309ace.png)
![storyboard 33](https://cloud.githubusercontent.com/assets/8978512/6337195/77ba2088-bb65-11e4-9e35-14f40077873a.png)
