### ISSUE TITLE
Fix UML

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#26]
![image1](https://cloud.githubusercontent.com/assets/9437242/6385209/27528db8-bd24-11e4-8024-2bd611ab9e5f.JPG)

Here's the photo from our meeting in case anyone wants to change the UML and reupload it

**Comment by vanbelle** [comment]
I just did a merge on the files we wanted to get rid of so that the classes left are the ones we chose in our UML design.

**Comment by vanbelle** [comment]
an updated png and dia file were added to https://drive.google.com/a/ualberta.ca/?tab=mo#folders/0B-TH6Ugp3srHSjYyUDNiVldacmc.

**Comment by vanbelle** [comment]
TA Comments:
1) Concept of MVC is not clear. Need to make clear distinctions between Model, View and Controller classes.
2) No comments were used anywhere in the diagram. You don't need comments for all the classes, but need for the confusing ones.
3) Multiplicity is totally absent. Roles in association are never labeled.
4) No use of generalization. A simple example would be to create a Model class 'User' which is inherited by claimant and approver. 
5) Where did you deal with local and remote store?

**Comment by vanbelle** [comment]
@megsum @LeahGabrielle @qsjiang @Pengwin-man @IchigoKIl 
I updated the activities that I worked on in the uml  stored in the drive, but didnt bother uploading it to wiki because everyone still has so many changes to make. The TAs said everything we have a class for should have something in the UML so we should really work on that this weekend.

**Comment by vanbelle** [comment]
Also, all classes that have serializable/listeners implemented need to have the lollipop thing.
eg: 
|-o serializable

**Comment by megsum** [comment]
![uml](https://cloud.githubusercontent.com/assets/6991742/6676186/987af748-cbeb-11e4-8ed9-3b8f4984c9ff.png)

**Comment by megsum** [comment]
![uml](https://cloud.githubusercontent.com/assets/6991742/6676213/ca844000-cbeb-11e4-953b-30a1bfea558f.png)

**Comment by Pengwin-man** [comment]
this looks so much more complicated than the one we had before. is this what they wanted?

**Comment by vanbelle** [comment]
Yes, except for your empty classes. He will probably want those filled in.

**Comment by megsum** [comment]
It's Fixed :D
