### ISSUE TITLE
User Stories / Test Cases

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#3]
US03.01.01 updated 2015-02-09
As a claimant, I want to give an expense claim one zero or more alphanumeric tags, so that claims can be organized by me into groups.

US03.02.01
As a claimant, I want to manage my personal use of tags by listing the available tags, adding a tag, renaming a tag, and deleting a tag.

US03.03.01
As a claimant, I want to filter the list of expense claims by tags, to show only those claims that have at least one tag matching any of a given set of one or more filter tags.

**Comment by Pengwin-man** [comment]
This issue has been resolved. Test cases were pushed 2 minutes ago. I am closing this issue.
