### ISSUE TITLE
 AddItem + Edit Item Activities

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#41]
- [x] clicking the date field opens up the date spinner - Sarah  
New  
- [x] clicking the currency field opens up currency menu
- [x] clicking the category field opens up the category menu
- [x] clicking the add photo taks the user to the built in camera app.  
Edit  
- [x] clicking the currency field opens up currency menu
- [x] clicking the category field opens up the category menu
- [x] clicking the add photo taks the user to the built in camera app.  

-----------------------------Just for Add Item Activity----------------------------------------
- [x] done button creates and adds new claim then returns to Claim Page

-----------------------------Just for Edit Item Activity----------------------------------------
- [x] set all text fields to their pre-exisiting values
- [x] done button updates expense item

**Comment by megsum** [comment]
Photos Finished!!!
