### ISSUE TITLE
Changes to Claim

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#53]
Based on some Prof. answers on eclass, claim no longer has a list of approvers but rather a single approver of type user. 

Becuase he said that only the original approver of a returned user can approve a returned claim I would like for this to be included in the filterByStatus function. Ideally when this function is called, it gets all submitted claims EXCLUDING those whose approver name does not match the username provided to the function.

**Comment by qsjiang** [comment]
@vanbelle  I will look into it.

**Comment by qsjiang** [comment]
Hi @vanbelle for the suggestion,

1. Out current implementation only allows one approver.  

2 . About controller,
In the next iteration, I will come up an more elegant solution for applying multiple filters in general, but for now I would suggest just manually loop through the array and remove those claims after you get the ArrayList <Claim>.

**Comment by IchigoKIl** [comment]
Please change Claim to utilize ExpenseList

**Comment by qsjiang** [comment]
@IchigoKIl
Will do

**Comment by qsjiang** [comment]
@IchigoKIl  
Hey Raymond, I saw the changes you made in expenseItem.class. You removed several functions construct strings 


First let me say they are GOOD changes. I 100% AGREE with you. 

but I don' think right now is a good time to break existing APIs since the due day is Monday. 

I think we should leave them inside the code for now and refactor them in next iteration.

**Comment by qsjiang** [comment]
@IchigoKIl  and can you explain the reason behind removing incomplete() function?

**Comment by IchigoKIl** [comment]
I was thinking that the controller can just as easily do the check by checking all the fields are not null.

**Comment by qsjiang** [comment]
@IchigoKIl  The current incomplete function is pretty messy, we definitely need to re-factor it, but I do think it should remain inside the expense class.

The reason being that "incomplete" is a status about the expense item. The model should be able to remember or figure out (compute on the fly) its current status without any help from the outside. 

but that's just my own personal opinion, we should discuss more on the next meeting.
