### ISSUE TITLE
Currently ExpenseItem's name under the same Claim needs to be unique, is this the behaviour we want?

### ISSUE THREAD

**Issue by qsjiang** [CMPUT301W15T12/C301Project#55]
Hey guys,

Currently ExpenseItem's name under the same Claim needs to be unique. 
That means you can not have two ExpenseItems with the same name inside one claim.

Is this the behaviour we want?

**Comment by vanbelle** [comment]
I dont think it really matters

**Comment by vanbelle** [comment]
I changed the code so it doesnt have to be.
