### ISSUE TITLE
**IMPORTATNT, MUST READ**  Using controllers from front-end code

### ISSUE THREAD

**Issue by Pengwin-man** [CMPUT301W15T12/C301Project#56]
Hi guys. it seems to me some of us are misunderstanding the need for controllers.

I have noticed that some of you in the front-end code writing have code similar to this:

UserlistController.getUserList().addUser();  << THIS IS ONLY FOR ME TO DO. Direct access to UserList. defeating the purpose of controllers

what you should be doing is this:

UserListController.addUser().   << this uses the controller to interface with the UserList Model and returns you the data you need.  please fix this as soon as possible.

please make sure this does not happen again.

**Comment by vanbelle** [comment]
Sure, I only left it like that so we could have something to run in the meantime.
