### ISSUE TITLE
Raymond please response to this. Please don't change your API the day before due day.

### ISSUE THREAD

**Issue by qsjiang** [CMPUT301W15T12/C301Project#57]
@IchigoKIl

Hey Raymond, I saw the changes you made in expenseItem.class. You removed several functions that construct strings. 

First let me say they are GOOD changes. I 100% AGREE with you. Those functions should not be there, but I don't think right now is a good time to break existing APIs since several classes are built on top of those apis, and the due day is tomorrow.

There are many problems we need to fix with the current APIs, and they will all be fixed eventually, but there are several steps we need to take when updating a critical api.

1 Tell your team why you need to make the change.
2 Inform them when the change will take place.
3  Add in the new API
4 mark the old api deprecated, but leave them inside the project for a "grace period"
5 if possible provide additional migration tutorials. 

We can't just surprise the team the day before due day and expect everyone to make the change.

**Comment by IchigoKIl** [comment]
I left the code in there, just commented out. I will uncomment it for now since it is causing a issue

**Comment by qsjiang** [comment]
@IchigoKIl  Thanks for the fast response. 

Also what's the reason behind deleting the incomplete() function inside ExpenseItem class.

Can you also bring back that function as well?

**Comment by IchigoKIl** [comment]
Sure

**Comment by qsjiang** [comment]
@IchigoKIl  There are still a few small syntax errors inside the ExpenseItem class, could you take look? 
![image](https://cloud.githubusercontent.com/assets/6367081/6660512/b3879662-cb60-11e4-826a-4c66adb005e0.png)

**Comment by IchigoKIl** [comment]
Looking into it right now

**Comment by IchigoKIl** [comment]
Should be fine now

**Comment by qsjiang** [comment]
@IchigoKIl  looking good. gj
