### ISSUE TITLE
Program crashed when creating a new user - null pointer exception 

### ISSUE THREAD

**Issue by qsjiang** [CMPUT301W15T12/C301Project#58]
Hi guys,

I am just playing around with the app right now, but when I try to create a new user, the program crashed with the following error

![image](https://cloud.githubusercontent.com/assets/6367081/6660708/a555a134-cb64-11e4-9fec-6a2c2db0e5f2.png)

Any idea what's causing the problem?

**Comment by vanbelle** [comment]
fixed
