### ISSUE TITLE
Expense Items / Overall

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#6]
US04.01.01
As a claimant, I want to make one or more expense items for an expense claim, each of which has a date the expense was incurred, a category, a textual description, amount spent, and unit of currency.

US04.02.01
As a claimant, I want the category for an expense item to be one of air fare, ground transport, vehicle rental, private automobile, fuel, parking, registration, accommodation, meal, or supplies.

US04.03.01
As a claimant, I want the currency for an expense amount to be one of CAD, USD, EUR, GBP, CHF, JPY, or CNY.

US04.04.01
As a claimant, I want to manually flag an expense item with an incompleteness indicator, even if all item fields have values, so that I am reminded that the item needs further editing.

US04.05.01
As a claimant, I want to view an expense item and its details.

US04.06.01
As a claimant, I want to edit an expense item while changes are allowed.

US04.07.01
As a claimant, I want to delete an expense item while changes are allowed.

US04.08.01
As a claimant, I want the entry of an expense item to have minimal required navigation in the user interface.

**Comment by LeahGabrielle** [comment]
I've put anything under this list in the wiki under Expense Items / Overall.
