### ISSUE TITLE
Meeting notes

### ISSUE THREAD

**Issue by LeahGabrielle** [CMPUT301W15T12/C301Project#61]
![img_2456](https://cloud.githubusercontent.com/assets/8978512/6701832/b0a8c8fc-cce7-11e4-8787-c1f4b8a4082c.JPG)  
 Here's what we decided everyone was doing at the meeting today and what needs to be done. So if you've forgotten what you said you would do look here!  
@Pengwin-man you can decide what you would like to work on this week - maybe write some test cases or add passwords to users? Those were some ideas that were tossed around at the meeting.

**Comment by vanbelle** [comment]
I don't mind implementing the passwords while I'm busy anyway. It should only take me 10minutes.

**Comment by Pengwin-man** [comment]
i can do the passwords since I am already working on users anyways
I can also finish off the user stuff and maybe work on some documentation?

**Comment by vanbelle** [comment]
I already implemented the add password throughout the code, I just havent pushed it because I wanted to wait until after the demo like we talked about. 

Why would we allow a user to be added without a password?
Right now we dont have anything that allows a user to change password after its created.

**Comment by Pengwin-man** [comment]
well, if a user does not want a password, why force one on him?  also, the fact that you implemented it throughout the code is irrelevant to the controller... i mean, the controller and model are mine are they not?  if you implemented it elsewhere it should not matter as long as you pass the correct arguments.

as for adding a change passoword, we can always easily do that later.

**Comment by vanbelle** [comment]
We can talk about it at the meeting on Tuesday. Was there something else you wanted to do until our next meeting on tuesday?
