### ISSUE TITLE
Bugs in add/edit Item

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#64]
@Megan, After my pull I had several errors associated to the pictures, I commented out the lines  causing the errors with a TODO so that they are easy to find back, but so that I could still test my code.

@Leah, Also tag manager is done but I had to create a new activity because it just wasnt working with multiple dialogs so that needs to go into the UML.

**Comment by megsum** [comment]
Weird. I uncommented the lines of code and still get no errors. Can I try pushing again with them uncommented?

**Comment by LeahGabrielle** [comment]
Try cleaning the project and refreshing the folder in the side column thing Sarah. The photo stuff seems to be working for me.
I will remember to put it in the UML when I work on it.

**Comment by vanbelle** [comment]
Sure. Maybe something is causing them, I'll check again tomorrow and post the error messages.

**Comment by megsum** [comment]
It works :+1:
