### ISSUE TITLE
NEW USER STORIES

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#65]
- [x] US10.01.01 added 2015-03-23
As a claimant, I want to set my home geolocation.

- [x] US10.02.01 added 2015-03-23
As a claimant, I want to specify a geolocation assisted by my mobile device (e.g., GPS) or manually using a map.

- [x] US10.03.01 added 2015-03-23
As a claimant, I want to view any set or attached geolocation using a map.

- [x] US05.01.01 updated 2015-03-23
As a claimant, I want to list all the expense items for a claim, in order of entry, showing for each expense item: the date the expense was incurred, the category, the textual description, amount spent, unit of currency, whether there is a photographic receipt, whether there is an attached geolocation, and incompleteness indicator.

- [x] US04.09.01 added 2015-03-23
As a claimant, I want to optionally attach a geolocation to an editable expense item, so I can record where an expense was incurred.

- [x] US02.03.01 added 2015-03-23
As a claimant, I want the list of expense claims to have each claim color code by the distance of its first destination geolocation to my home geolocation, so that claims for distant travel can be distinguished from claims for nearby travel.

- [x] US01.07.01 added 2015-03-23
As a claimant, I want to attach a geolocation to a destination.

**Comment by vanbelle** [comment]
Right now, everything works so long as they only want to use their current location, remote locations still need to be implemented.

**Comment by megsum** [comment]
Everything but viewing should work now!
