### ISSUE TITLE
Extra features

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#67]
features to add if we have time?
- [ ] logout function
     - I would add this option in every menu
     - resets the system and brings the user back to the login page 

- [ ] edit user account
    - also add this feature in every menu
    - here the user could change username, password, and geolocation

Any Others?

**Comment by qsjiang** [comment]
Please leave username alone. 

Username is the single unique ID we have to identify a user object. 

Inside the android app, changing username is perfectly fine.  Its a wonderful object oriented world where objects are copied by reference. 

but once the data is sterilized into json and uploaded onto the server you loss this memory reference provided by JVM. The only way left for the JSON objects to find it's "Mommy" is by checking against the that username.

**Comment by vanbelle** [comment]
ok, lets leave out the extra features then.
