### ISSUE TITLE
Bugs to fix

### ISSUE THREAD

**Issue by megsum** [CMPUT301W15T12/C301Project#69]
Hey I thought it would be a good idea to list bugs that our app has so that we know what still needs to be fixed.
- [x] If we search by two tags that are in the same claim, that claim will appear twice
- [x] If you edit an expense and click on the photo and cancel it deletes the previous photo
- [x] Claim end date needs to be after start date
- [x] item not showing up

**Comment by vanbelle** [comment]
I will fix the tags tomorrow.

**Comment by LeahGabrielle** [comment]
when adding a claim, the system should tell me if my end date is less than my start date !!! This was missing.
End date must be greater or equal to the start date.. 

1.04.01: is it really covered.. was not working for me !!!

US02.02.01: It should be in opposite order.. most recent to oldest.. !!

I can add zero, one or more tags.. good.. but after adding them, I can't see what was added before saving.. 

Would not it be better to enable the Flag options while creating the item for the first time as well??

Editing expense item has problems.. for example, if I try to edit an item and then press done, it does not show the changes !! although if I go back
to the original interface, I can see the changes.. this is very confusing for your product's users... 

I can not see anywhere how to submit my claims or approve it although you said they are implemented.. !!!! what's wrong here..

**Comment by vanbelle** [comment]
- [ ] Can't add incomplete expense items when the incomplete fields are currncy/category.
