### ISSUE TITLE
Expense Items / Receipt

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#7]
US06.01.01
As a claimant, I want to optionally take a single photograph of a receipt and attach the photograph to an editable expense item, so that there is supporting documentation for the expense item in case the physical receipt is lost.

US06.02.01
As a claimant, I want to view any attached photographic receipt for an expense item.

US06.03.01
As a claimant, I want to delete any attached photographic receipt on an editable expense item, so that unclear images can be re-taken.

US06.04.01
As a sysadmin, I want each receipt image file to be under 65536 bytes in size.

**Comment by qsjiang** [comment]
Completed inside the following commits:

6ac5d4c7bf5abe49274e9d3f1f069cbf828f10ec
113009e3d2f711362dbd8bfe9dc836431728179e
1e95553dbab8880bdfe587cc75979eccfe17f91d
38636e17fc9cd59be54263cc55c5906727bbb682
11887a3877d104ea85c25e2097f2161c66fc6302
967500daf4c8eb74971736dbaeb9f4f5c1f06ebd
8552af6e238a8f7dd5b62c5dc6a060d355a7ca9d
cfb36eed7585ddda242a471ab98b2749055f5fb0
0bd343171491870ad97ca1ed1ee7d92f7347a3e6

Ya I know thats a lot of commits, but I prefer to commit in small steps. The way the commit message can clearly defines what exactly is going on inside the commit.  : P
