### ISSUE TITLE
App crashes when click on "create new user" button

### ISSUE THREAD

**Issue by qsjiang** [CMPUT301W15T12/C301Project#71]
The app crashed when I clicked on  "create new user" button.

It says  "gps" location provider requires ACCESS_FINE_LOCATION permission. 
I checked the manifest file, and we have the correct permission strange... 

Could someone please take a look? 

Here is the full stack trace.
04-01 07:22:03.469: E/AndroidRuntime(1560): FATAL EXCEPTION: main
04-01 07:22:03.469: E/AndroidRuntime(1560): java.lang.RuntimeException: Unable to start activity ComponentInfo{ca.ualberta.cs.cmput301w15t12/ca.ualberta.cs.cmput301w15t12.NewAccountActivity}: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.os.Looper.loop(Looper.java:137)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at java.lang.reflect.Method.invoke(Method.java:525)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at dalvik.system.NativeStart.main(Native Method)
04-01 07:22:03.469: E/AndroidRuntime(1560): Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.os.Parcel.readException(Parcel.java:1431)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.os.Parcel.readException(Parcel.java:1385)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:540)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:836)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:430)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at ca.ualberta.cs.cmput301w15t12.NewAccountActivity.onCreate(NewAccountActivity.java:126)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.app.Activity.performCreate(Activity.java:5133)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
04-01 07:22:03.469: E/AndroidRuntime(1560): 	... 11 more

**Comment by vanbelle** [comment]
What happens when you run the gps program from the lab? Does that work on your computer?

**Comment by qsjiang** [comment]
@vanbelle  I only tried on my local machine.
