### ISSUE TITLE
Fatal Login Crash

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#74]
I get this error when I try running the app, it looks like a server issue.

04-04 21:36:26.292: E/AndroidRuntime(4204): FATAL EXCEPTION: AsyncTask #1
04-04 21:36:26.292: E/AndroidRuntime(4204): java.lang.RuntimeException: An error occured while executing doInBackground()
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at java.lang.Thread.run(Thread.java:856)
04-04 21:36:26.292: E/AndroidRuntime(4204): Caused by: java.lang.StackOverflowError
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:380)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:375)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:355)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:117)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.Gson.getAdapter(Gson.java:353)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.Gson.getAdapter(Gson.java:353)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.Gson.getAdapter(Gson.java:353)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
04-04 21:36:26.292: E/AndroidRuntime(4204): 	at com.google.gson.

**Comment by vanbelle** [comment]
@qsjiang when i click the save to server option in the claimlist menu the system crashed

what does the calling:
	//menu item save claim	
	public void saveClaim(MenuItem menu) {
		new ESClient().saveRecordToServer();
	}

here is the stack trace

04-05 23:16:17.433: E/AndroidRuntime(9565): FATAL EXCEPTION: main
04-05 23:16:17.433: E/AndroidRuntime(9565): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.view.MenuInflater$InflatedOnMenuItemClickListener.onMenuItemClick(MenuInflater.java:234)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:144)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:156)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2749)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.widget.AbsListView$1.run(AbsListView.java:3423)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.os.Handler.handleCallback(Handler.java:725)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.os.Handler.dispatchMessage(Handler.java:92)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.os.Looper.loop(Looper.java:137)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.app.ActivityThread.main(ActivityThread.java:5039)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at java.lang.reflect.Method.invoke(Method.java:511)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at dalvik.system.NativeStart.main(Native Method)
04-05 23:16:17.433: E/AndroidRuntime(9565): Caused by: java.lang.reflect.InvocationTargetException
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at java.lang.reflect.Method.invoke(Method.java:511)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.view.MenuInflater$InflatedOnMenuItemClickListener.onMenuItemClick(MenuInflater.java:230)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	... 16 more
04-05 23:16:17.433: E/AndroidRuntime(9565): Caused by: android.os.NetworkOnMainThreadException
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1117)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at java.net.InetAddress.getAllByName(InetAddress.java:214)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at ca.ualberta.cs.cmput301w15t12.ESClient.saveRecordToServer(ESClient.java:59)
04-05 23:16:17.433: E/AndroidRuntime(9565): 	at ca.ualberta.cs.cmput301w15t12.ChooseListActivity.saveClaim(ChooseListActivity.java:78)

**Comment by qsjiang** [comment]
04-05 23:16:17.433: E/AndroidRuntime(9565): Caused by: android.os.NetworkOnMainThreadException


the problem is self explanatory.   Just do it like I showed you in my previous issues. 


new LoadingOnlineRecordTask().execute();   //put this inside oncreate
turnOnSpinner();  //fake pseudo code

//AsyncTask For loading records from Elastic Server
private class LoadingOnlineRecordTask extends AsyncTask<Void, Void, Void> {
    @Override
    protected Void doInBackground(Void... optionalInputs) {
        new ESClient().loadRecordFromServer();
        return null;
    }
    @Override
    protected void onPostExecute(Void result) {
                    turnOffSpinner(); //fake pseudo code
        ClaimListController claimListController = new ClaimListController();
        Toast.makeText(LoginActivity.this,"Loaded: "+claimListController.size()+" claims "+UserList.users.size()+" users", Toast.LENGTH_SHORT).show();       
    }  
}
