### ISSUE TITLE
Map Not showing up.

### ISSUE THREAD

**Issue by Pengwin-man** [CMPUT301W15T12/C301Project#75]
Hey guys. I am not sure if this issue has been solved as i could not find anything in the issues, but i took a look at the code and cannot seem to find the error.  could it be that we are using the methods in a way that they are not meant to be used?

On a side note,  I made some updates to the release plan, and was working on refactoring when i got sick.  Not sure how much i can do right now.,

**Comment by megsum** [comment]
I did make an issue saying I fixed this. All good

**Comment by LeahGabrielle** [comment]
Did you get any refactoring done? If you did, could you add it to the refactoring wiki page?
