### ISSUE TITLE
Weekend Group Meeting

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#76]
Would everyone be able to meet for a couple hours on monday to make sure we have everything?

Check your name if you can and edit what times you could be here
- [x] Sarah - Anytime
- [x] Leah - Anytime
- [x] Raymond - 
- [ ] Jim - 
- [ ] Megan - 
- [ ] Omar - 

Or Sunday
- [x] Sarah - Anytime
- [x] Leah - 10AM - 5PM
- [x] Raymond - 
- [ ] Jim - 
- [x] Megan - Until 6:00
- [ ] Omar -

**Comment by megsum** [comment]
I have Easter dinner on Monday starting at 2:30 :(. The only day I could meet is Sunday

**Comment by vanbelle** [comment]
Can we tentatively agree to meet around 10 tomorrow? It would be good if we could get everything straightened out so that we can do the video, and the other things that have been waiting on a finished final product.

**Comment by megsum** [comment]
We never had a meeting :(
