### ISSUE TITLE
final UML

### ISSUE THREAD

**Issue by LeahGabrielle** [CMPUT301W15T12/C301Project#77]
Here's (what I hope) the final UML is. Have a look, and if you spot anything that's changed or that I've done wrong, let me know.
![uml-march30](https://cloud.githubusercontent.com/assets/8978512/6998387/0688444e-db9f-11e4-9348-c6a10d3b0810.png)

**Comment by LeahGabrielle** [comment]
uploading mockup
![storyboard](https://cloud.githubusercontent.com/assets/8978512/6998469/73e0e7ce-dba1-11e4-9ecd-25407646b88e.png)
![storyboard 1](https://cloud.githubusercontent.com/assets/8978512/6998470/7541fdce-dba1-11e4-96b0-f9d7cc1f6ba2.png)
![storyboard 2](https://cloud.githubusercontent.com/assets/8978512/6998471/77e9c00c-dba1-11e4-8acf-de76e6e51680.png)
![storyboard 3](https://cloud.githubusercontent.com/assets/8978512/6998472/7a52d400-dba1-11e4-97a7-65e0c8ea7aff.png)
![storyboard 4](https://cloud.githubusercontent.com/assets/8978512/6998474/7ece3d8a-dba1-11e4-827c-1a2b07e52280.png)
![storyboard 5](https://cloud.githubusercontent.com/assets/8978512/6998475/80a6d3b0-dba1-11e4-8907-151d205d7c46.png)
![storyboard 6](https://cloud.githubusercontent.com/assets/8978512/6998479/85f00f62-dba1-11e4-9c6b-179a1afb218e.png)
![storyboard 7](https://cloud.githubusercontent.com/assets/8978512/6998478/85de6c12-dba1-11e4-8d6e-387895b7738b.png)

**Comment by LeahGabrielle** [comment]
new storyboard 
![storyboard-2 12](https://cloud.githubusercontent.com/assets/8978512/7013640/77d8a434-dc78-11e4-82b1-f65a4139d193.png)
![storyboard-2 13](https://cloud.githubusercontent.com/assets/8978512/7013646/795cd816-dc78-11e4-8c17-177ddf752488.png)
![storyboard-2 14](https://cloud.githubusercontent.com/assets/8978512/7013650/80af328a-dc78-11e4-96c7-058ce39d0891.png)
![storyboard-2 15](https://cloud.githubusercontent.com/assets/8978512/7013652/8487e6e0-dc78-11e4-8b98-7c4d6509cadf.png)
![storyboard-2 16](https://cloud.githubusercontent.com/assets/8978512/7013657/89815ec4-dc78-11e4-9d12-badf57ccb2f8.png)
![storyboard-2 17](https://cloud.githubusercontent.com/assets/8978512/7013658/8b838f3a-dc78-11e4-9f2e-9f97a683bd5a.png)
![storyboard-2 18](https://cloud.githubusercontent.com/assets/8978512/7013660/8d75fdd2-dc78-11e4-9a4b-f48cf3bfa912.png)
![storyboard-2 19](https://cloud.githubusercontent.com/assets/8978512/7013662/8f4512f6-dc78-11e4-95c0-0ada138c362c.png)
![storyboard-2 20](https://cloud.githubusercontent.com/assets/8978512/7013663/91799f88-dc78-11e4-89f3-032b1cf61e7a.png)

**Comment by vanbelle** [comment]
These storyboards look really great! :+1:

**Comment by LeahGabrielle** [comment]
test
![uml-march30-fix](https://cloud.githubusercontent.com/assets/8978512/7031442/d124b1e4-dd28-11e4-9075-93727c934f40.png)
