### ISSUE TITLE
Meeting This Tuesday!

### ISSUE THREAD

**Issue by LeahGabrielle** [CMPUT301W15T12/C301Project#78]
Just a reminder that we're having the regular meeting this Tuesday (April 7). We are going to practice the lab presentation so that we can make all the other groups envy our fantastic presentation skills.

**Comment by IchigoKIl** [comment]
I'm sorry to say this but I will be in Calgary on that day, and won't be able to make it to the meeting. I can ask Omar to fill me in on Wednesday.

**Comment by Pengwin-man** [comment]
yeah. ill be at the meeting on Tuesday. Ill fill him in and let him know how the presentation is going to go afterwards.

**Comment by LeahGabrielle** [comment]
:+1:

**Comment by LeahGabrielle** [comment]
So we can meet at 4 since Raymond won't be here if that works for everyone, unless someone else had something at 4. I've booked csc 3-26 for half an hour at 4. @Pengwin-man @qsjiang @megsum @vanbelle @IchigoKIl

**Comment by Pengwin-man** [comment]
4 sounds great.  That way we can go. Home early

**Comment by LeahGabrielle** [comment]
Sorry Omar, Jim said he couldn't meet until 5. One last 5 o'clock meeting

**Comment by Pengwin-man** [comment]
Cool
