### ISSUE TITLE
Implementing string arrays in resource file

### ISSUE THREAD

**Issue by IchigoKIl** [CMPUT301W15T12/C301Project#79]
I believe I have a working solution, but am unable to set the gps on the emulator to create an account to login and test it. Can someone tell me a account that's already set up?

**Comment by vanbelle** [comment]
If you look at the esclient page there is a url to a website where you should be able to see everything that's saved.

**Comment by IchigoKIl** [comment]
I have just tested it and it is working correctly. Is AddItemActivity the only activity that uses the category and currencies spinner?

**Comment by vanbelle** [comment]
Yes
