### ISSUE TITLE
Refactoring the code.

### ISSUE THREAD

**Issue by Pengwin-man** [CMPUT301W15T12/C301Project#80]
I was doing some re-factoring, and noticed that unless we want a class for EVERY attribute in our Data models, i do not think it necessary to do any more.  the code is fine the way it is.  The refactorings offered by JDeodorant are only useful if we had to manipulate the data in the attributes with methods other than getters and setters.

**Comment by megsum** [comment]
Hey! So the refactoring that you did do, can you put it on the wiki page?

**Comment by vanbelle** [comment]
Yeah, I need to do the write up today or tomorrow so it would be helpful to know what was changed so that I could add that in there.
