### ISSUE TITLE
Question about saving

### ISSUE THREAD

**Issue by IchigoKIl** [CMPUT301W15T12/C301Project#81]
How do I save my progress on the app? When I create a new account and submit a new claim, and then close the app my account is gone... What should I be doing to save?

**Comment by qsjiang** [comment]
@vanbelle will be implementing a "saving to server" button inside the top right menu.

Not saving records automatically is a design decision we made for minimizing the impact on existing api.

**Comment by Pengwin-man** [comment]
when was this decision made? i think it is a bad decision.  its too late to change it now, but given the scope of the app, one would think that an account creation is saved once you click create account.

**Comment by qsjiang** [comment]
Hi @Pengwin-man The decision was made on Thursday when you missed the lab meeting.

" one would think that an account creation is saved once you click create account." 
I think so as well. Technically any add/change to model should be saved to the server right away.

In fact the first version of the ESClient I wrote does exactly that, but the code that communicate with the server are internet calls, and can not be called directly like other apis(requires AsyncClass)

That means all the activities will have to implement asyncclass when modifying/adding/deleting claims, and users

**Comment by vanbelle** [comment]
This has been implemented and pushed, but I only added it so far in the claimlist menu, if we want it elsewhere let me know and we can create some other menu items.
