### ISSUE TITLE
Power Use Estimation

### ISSUE THREAD

**Issue by IchigoKIl** [CMPUT301W15T12/C301Project#82]
This section of the assignment asks to estimate the power use of the app using green advisor, but from what I've seen the report shows the percentage change in the number of calls of significant system calls between two commits. Does anyone understand what should be done for this section of the assignment?

**Comment by LeahGabrielle** [comment]
There was something about this on eclass. "You should just pick two commits and compare them using the tool." So just pick two commits and run it, then describe it on the wiki it sounds like.   
**Power Use Estimation:**  Try to estimate the power use of your application using the green advisor tool provided in the labs. Describe the output of the tool 1 reasonable paragraph provided on the wiki. The tool database and the the reports it generate should be committed to your git repo.
