### ISSUE TITLE
Editing tags on a submitted expense

### ISSUE THREAD

**Issue by LeahGabrielle** [CMPUT301W15T12/C301Project#83]
Do we have anything in place to edit tags of a claim when its status is submitted? 
[US07.01.01] -  As a claimant, I want to submit an expense claim for approval, denoting the claim status as submitted, with no further changes allowed by me to the claim information **(except the tags).**
Or have we chosen to not do this? I know it's probably a bit late to implement it now if it is not already there.

**Comment by vanbelle** [comment]
I will add a menu item to the claim menu if i have time today, it shouldnt be too hard to fix.

**Comment by vanbelle** [comment]
This should be working now

**Comment by vanbelle** [comment]
also added a text view to see the tags on the claim page
