### ISSUE TITLE
Integrated online photo saving

### ISSUE THREAD

**Issue by qsjiang** [CMPUT301W15T12/C301Project#84]
Hi @megsum, 

I just integrated the photo saving, so far it works fine, but there are quite a lot of stuffs going on inside additemActivity class. I figured it's best to ask the original author to take a look. 

Here is the commit with all the related changes 
fbe692fe07195d8b7864bfe3796096cc0839a076

I am free tomorrow after 1pm. If you have time we should meet and go over the changes.

**Comment by megsum** [comment]
Okay sounds good! I will look at it now!

**Comment by qsjiang** [comment]
@megsum cool

**Comment by megsum** [comment]
@qsjiang  I am not too sure how the client stuff works, but it looks like you changed where it needs to be changed! From what I can see it makes a temporary location that stores the photo and then uploads it to the server from there. If so it looks good!

**Comment by qsjiang** [comment]
ya. The previous Uri saved inside expenseItem was just a local file pointer. 
Now it's a relative path on the elastic server. 
The temp uri is just a temp location for saving the output from the camera app.

**Comment by vanbelle** [comment]
I'm getting an error in the one of the photo tests now, don't forget to update that so it works in the tests too.

**Comment by megsum** [comment]
I haven't done the photo tests yet so it is all good. (Except that the photo tests aren't done yet) :(
